### ISSUE TITLE
1.0 release

### ISSUE THREAD

**Issue by mwjames** [onoi/message-reporter#1]
@JeroenDeDauw I'd like to put a 1.0 label on this (given the fact that there are no objections) so we can replace the `SMW\Reporter` stuff in SMW.

**Comment by JeroenDeDauw** [comment]
Hmmm... no objections.

I have to say I've not used this interface in quite some time.

A reason for this being that while you decouple what is done with the string message, you still need to construct the string. Doing that is a presentation task, so you typically do not want to do this where the message is send.

I'm now more inclined to create a specific event interface such as https://github.com/wmde/WikibaseQueryEngine/blob/master/src/Importer/ImportReporter.php which is then used in https://github.com/wmde/WikibaseQueryEngine/blob/master/src/Importer/EntitiesImporter.php and implemented for instance as https://github.com/wmde/WikibaseQueryEngine/blob/master/src/Console/Import/CliImportReporter.php

Or if you can't be bothered to make the specific interface, or simply don't care about the additional explicitness of the custom interface, use something like the Symfony EventDispatcher https://github.com/symfony/EventDispatcher

**Comment by JeroenDeDauw** [comment]
That does not mean this interface is not a good approach in some situations. It is however less generally useful as I used to think when I wrote it.

**Comment by mwjames** [comment]
> That does not mean this interface is not a good approach in some situations. It is however less generally useful as I used to think when I wrote it.

If we come to believe that something needs to be replaced by something else at a later point then this is fine but currently I'm on a "crusade" that simple stuff that doesn't have a particular SMW "smell" gets an interface and is being out-factored (well the DB thing is a more complex discussion).

> Or if you can't be bothered to make the specific interface, or simply don't care about the additional explicitness of the custom interface, use something like the Symfony EventDispatcher https://github.com/symfony/EventDispatcher

Currently I'm a bit reserved to introduce a dependency to something like symfony (DBAL is already huge if introduced), so I'd rather see us to use a middle man ("wrapper") that points to those large dependencies and narrows it down to the point where it makes sense or to have a "small" dependency like this one that doesn't dependent on anything else.

**Comment by JeroenDeDauw** [comment]
Size is a factor in determining how much of a livability a dependency is. Though IMO not the biggest one. In some cases it seems hardly relevant. For instance take the MSSQL and Oracle code in DBAL. Perhaps we don't have a use for it, but are we hurt by it being there? Only a very tiny bit I'd say.

The number of people that will get mad if something goes wrong with the dependency, and the number of people that can do something about it, is very important. If something we use from DBAL breaks, it's very likely it will be fixed quickly by someone. It's unlikely we'll ever get to see the break. Compare that to an interface and some stuff we put into our own package and that no one but us uses, and no one but us contributes to or is familiar with the code.

If you need a library for a general task, it's very likely it's already solved well by some package. A package that is well maintained. In such a case it seems a lot more economical to use that instead of reinventing the wheel once again.

I'd expect nearly all packages we create for the SMW project to be SMW specific or be special in some way that makes them not already be solved problems.

Good blog post on the topic: https://philsturgeon.uk/php/2014/10/20/php-wars-attack-of-the-clones/

PS: I think it was a big mistake to introduce Validator/ParamProcessor as a dependency to SMW way back. I'd say technically we did not gain more worth than cost from it. Plus we now have it as a liability. And it made life harder for users.
